persistence:
  defaultStore: postgres-default
  visibilityStore: postgres-visibility
  datastores:
    postgres-default:
      sql:
        pluginName: "postgres"
        databaseName: "cadence"
        connectAddr: "127.0.0.1:5432"
        connectProtocol: "tcp"
        user: "postgres"
        password: "cadence"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
    postgres-visibility:
      sql:
        pluginName: "postgres"
        databaseName: "cadence_visibility"
        connectAddr: "127.0.0.1:5432"
        connectProtocol: "tcp"
        user: "postgres"
        password: "cadence"
        maxConns: 2
        maxIdleConns: 2
        maxConnLifetime: "1h"