persistence:
  defaultStore: mysql-default
  visibilityStore: mysql-visibility
  datastores:
    mysql-default:
      sql:
        pluginName: "mysql"
        databaseName: "cadence"
        connectAddr: "127.0.0.1:3306"
        connectProtocol: "tcp"
        user: "root"
        password: "cadence"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
    mysql-visibility:
      sql:
        pluginName: "mysql"
        databaseName: "cadence_visibility"
        connectAddr: "127.0.0.1:3306"
        connectProtocol: "tcp"
        user: "root"
        password: "cadence"
        maxConns: 2
        maxIdleConns: 2
        maxConnLifetime: "1h"